### ISSUE TITLE
cSNP tool 

### ISSUE THREAD

**Issue by mugitty** [pantherdb/features-bugs#23]
tips popup at pantherdb.org/tips/tips_exampleCsnpInput.jsp#substitutions, the example SNPs are:
L46P
R130C
R163C
C176R

But they should be:
L46P
C130R
R163C
R176C

“e.g. A10P”, which doesn’t correspond to example in the tips popup, should be “e.g. L46P” instead

“begign”, which is a misspelling should be “benign” - This is from the cSNP script not website.

Question - , is there a number value that is returned by the cSNP scoring program other than the preservation time?

**Comment by mugitty** [comment]
I have resolved the label issues on the website.


@dustine32, could you please update since you maintain them? there is a typo in the cSNP output:

“begign”, which is a misspelling should be “benign” - This is from the cSNP script not website.

I found it in  csnp_analysis.pl

 grep begign  csnp_analysis.pl
        $messge ="probably begign";

@thomaspd also had a question - is there a number value that is returned by the cSNP scoring program other than the preservation time?

**Comment by dustine32** [comment]
@mugitty Just fixed the typo in `csnp_analysis.pl`.

**Comment by dustine32** [comment]
There is an `$age` variable that determines the returned message (e.g. "probably benign", "possibly damaging"). I can return this $age value in the XML response.

**Comment by mugitty** [comment]
@dustine32 , please return $age as part of the response.   Let me know when you have pushed the change to production.

**Comment by dustine32** [comment]
@mugitty Looking at the code, I think the `$age` value is already coming through the `<subPSEC>` tag in the response. I was able to get an example XML response:
```
<snp_analysis>
  <hmm_info>
    <hmm_acc>PTHR18976</hmm_acc>
    <hmm_score>NA</hmm_score>
  </hmm_info>
  <snp_score>
      <subPSEC>220</subPSEC>
      <wt_aa>R</wt_aa>
      <mut_aa>C</mut_aa>
      <protPos>163</protPos>
      <snp_msg>possibly damaging</snp_msg>
  </snp_score>
</snp_analysis>
```
So, `220` is the `$age`, not sure of the units though (million years?).

**Comment by thomaspd** [comment]
Yes, it's age in millions of years. The snp_msg is based on probability thresholds we determined empirically from a graph of testing data-- each value of subPSEC should have an associated probability of being a damaging mutation. I was hoping the probability was one of the outputs, but it looks like it isn't. I'll need to look for the graph we used to convert the age into a probability.

**Comment by mugitty** [comment]
@thomaspd , do you want me to add the age i.e. information from subPSEC tag to the output?

**Comment by thomaspd** [comment]
It's already displayed on the PANTHER site as the "preservation time"

**Comment by mugitty** [comment]
Sorry for the confusion

**Comment by thomaspd** [comment]
OK, I've figured out how to convert the "age" to a probability. The probability should be an output from the perl script, so that if a user downloads the tool and runs it, they'll get this probability as well. We'll call the probability Pdel (probability that the mutation is deleterious). 

On the PANTHER website, we'll add a column to the results page, with the header "Pdel" and add a sentence to the explanatory text at the bottom of the results box. The new text will be:
PSEP (position-specific evolutionary preservation) measures the length of time (in millions of years) a position in current protein has been preserved by tracing back to its reconstructed direct ancestors. The longer a position has been preserved, the more likely that it will have a deleterious effect. We convert this to a probability of deleterious effect (Pdel) from results on the HumVar benchmark. We convert this Pdel to a qualitative prediction as follows: "probably damaging" (time > 450my, corresponding to a false positive rate of ~0.2 as tested on HumVar), "possibly damaging" (450my > time > 200my, corresponding to a false positive rate of ~0.4) and "probably benign" (time < 200my). 

Here's the table for converting age to Pdel
age          Pdel
0-25        0.02
26-85      0.13
86-91      0.17
92-99      0.19
100-199   0.27
200-399  0.50
400-699  0.57
700-799   0.74
800-899   0.78
900-1299  0.85
1300-1599  0.86
1600-3999  0.89
4000 or more  0.95

**Comment by mugitty** [comment]
@dustine32 , let me know when the script has been updated to output Pdel.

**Comment by dustine32** [comment]
@mugitty Yeah, I can add it. I should see if this script is version-controlled in GH or somewhere.

**Comment by dustine32** [comment]
@mugitty FYI, Pdel not added yet but I have it in progress in new repo https://github.com/pantherdb/cSNP_analysis. I'll shout once it's ready.

Also, the XML output code looks like it's already returning a `<pdeleterious>` tag, though it's always empty. Can I just return the Pdel in that tag?

**Comment by mugitty** [comment]
@dustine32, thanks for the status.

I looked at the code and the XML parser reads contents of the <pdeleterious> tag into a variable of type double, if it is not empty. You can use this variable.

I will update the web page to output this variable.

**Comment by dustine32** [comment]
Hey @mugitty the service should now be returning the `pdeleterious` value in the XML. Lemme know if you encounter any problems.

I also opened this issue here: https://github.com/pantherdb/cSNP_analysis/issues/1

**Comment by mugitty** [comment]
@dustine32 and @thomaspd .  I have updated the code to output Pdel and also the text.  I noticed that we have tips that describe the table columns in detail (http://pantherdb.org/tips/tips_csnpScores.jsp#results).  I want to update this as well before pushing to production.

@thomaspd , for Pdel, I want to add the following:
 This is the probability that the mutation is deleterious from results on the HumVar benchmark

Do you want to modify to something else?

**Comment by thomaspd** [comment]
I think you've covered everything. Small change to your text for Pdel:
This is the probability that the mutation has a deleterious effect on function, as estimated from results on the HumVar benchmark.

Please hyperlink the text "HumVar benchmark" to https://pubmed.ncbi.nlm.nih.gov/16895930/

**Comment by mugitty** [comment]
Thanks @thomaspd !

The update is now in production.

@huaiyumi, the results page now has the extra information requested by feedback.
